### ISSUE TITLE
Como tratar infratores

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#10]
Existem vários tipos de infração. Os moderadores tomarão decisões baseadas nas regras, levando em consideração o nível ou recorrência da infração.

Para todas as opções, as opções serão:

A. Remover o post e banir automaticamente
B. Alerta no post, sugerindo sua leitura das regras e remoção do post
C. Remoção do post ou comentário, sem banir o usuário
D. Deixar rolar

Como o grupo deverá tratar os infratores
1. **Não intencional** - Usuário recém chegado ainda não leu as regras.
2. **Intencional** - Usuário já conhece as regras, mas as infringiu.
3. **SPAM** - Um bot postou SPAM no grupo.
4. **Brigas no grupo** - Uma discussão causou uma briga no grupo.
## 
#### Votação

| Usuário | 1 | 2 | 3 | 4 |
| --- | --- | --- | --- | --- |
| @brunogasparetto | ? | ? | ? | ? |
| @drgomesp | B | A | A | D |
| @henriquemoody | B | A | A | D |
| @kinncj | B | A | A | D |
| @rogerioadris | B | A | A | D |

**Comment by kinncj** [comment]
- Alerta no post, sugerindo sua leitura das regras e remoção do post + Se possível, alerta por MSG direta.

Tratamento aos infratores
- 2 , a definição de grupo diz que antes de interferir no funcionamento do mesmo, deve-se estar ciente das regras... entrar sem ao menos procurar algum tipo de regra, se chama casa da mãe joana e não grupo.
- 3 , temos alguns casos de SPAM.
- 4 , não aprecio nada que não seja construtivo.

**Comment by drgomesp** [comment]
##### 1. **Não intencional** - Usuário recém chegado ainda não leu as regras.

Alerta no post, sugerindo sua leitura das regras, mas mantendo a linha de pedir para que o próprio usuário remova o post.

##### 2. **Intencional** - Usuário já conhece as regras, mas as infringiu.

Remoção e Ban.

##### 3. **SPAM** - Um bot postou SPAM no grupo.

Remoção e Ban.

##### 4. **Brigas no grupo** - Uma discussão causou uma briga no grupo.

Deixa rolar.

**Comment by brunogasparetto** [comment]
4 - caso seja uma briga só de ofensas importante alertar e remover, caso os usuários insistam na discussão em novo tópico até vale a pena dar um gelo neles. Se for só pessoal mais "empolgado" em defender alguma funcionalidade ou qualquer coisa assim não vejo problemas

**Comment by henriquemoody** [comment]
Coloquei meu voto na descrição da issue, acho que deveríamos adicionar o item **Xingamentos**, **Ofensas diretas** ou coisa assim ou podemos discutir esse assunto na issue #8.

**Comment by rogerioadris** [comment]
1.  B
2. A
3. A
4. D

**Comment by brunogasparetto** [comment]
1 - B
2 - B
3 - A
4 - D

Bom, quanto ao item 2 é complicado saber se é intencional ou não de primeira. Caso o admin saiba que é um caso realmente intencional voto por excluir e banir mesmo.

Quanto às brigas acho bom só remover ou intervir caso vire ofensa.

**Comment by renatomefi** [comment]
1. B
2. C, na 3ª reincidência, A
3. A
4. D

**Comment by ogunhe** [comment]
1 - C (um cara que entra num grupo de discussão e não lê regra tem de ter o post excluído)
2 - A (trollagem...)
3 - A (no comments)
4 - D (a não ser que sejam ofensas e tal)

**Comment by eltonoliver** [comment]
1. B
2. A
3. A
4. D

**Comment by jackmakiyama** [comment]
1: B

2: C ou B
Da pra tolerar dependendo do nivel da infração instruindo a pessoa: B
E se o mesmo continuar insistindo no coco que fez: C
Se já fez alguma vez e fazer denovo: C

3: B
Se foi um bot que postou então não foi o usuario do grupo em si, já rolou de um usuario "participante" aceitar esses bot de algum modo e postar em varios grupos.

Se for um usuario fake, ai sim C

4: D
Deixa rolar, se for produtivo com certeza deixa rolar,
Só não curto quando postam coisas que é só pra causar bosta, igual o Suissa faz.

**Comment by filipiarruda** [comment]
Essa questão é bem polêmica, mas acho que no caso, o moderador, deve usar meio que uma jurisprudência, avaliar a situação em sí, e ver qual se encaixa melhor, talvez até dando alertas em casos específicos, e se notar uma frequência ou repetir as ofensas, daí sim o banimento é o justo.

**Comment by walkeralencar** [comment]
1: B
- Unanimidade...
  2: B/A
- Começa com B (2a chance),  em caso de reincidência A.
  3: B/A
- Se é BOT, B (2a chance),  em caso de reincidência A. como o @jackmakiyama  citou.
  4: D 
  do {
  D(); //deixa rolar
  } while ( in_array($comportamento, array( 'produtivo', 'respeito') ) );
