### ISSUE TITLE
Exploração de debates e ajuda na compreensão de funcionalidades

### ISSUE THREAD

**Issue by Soufraz** [php-brasil/Documentos#13]
Sei que a comunidade e documentação do php hoje é incrível e não existe dificuldade quase nenhuma em estudar/descobrir como se utiliza alguma função da linguagem.
Infelizmente - não me recordo especificamente os casos - já visualizei posts em usuários querendo entender como funciona ou qual a melhor forma de utilizar determinada função no php e os membros meio que deixar a passar despercebido. Sempre colando links pra a documentação (que não deixa de ser uma ajuda) ou 'procure antes de postar'. 
Concordo que a busca na documentação é um fator importante na aprendizagem (obvio). Mas as vezes uma dúvida pode gerar um discussão interessante para todos os membros do grupo.
Saber a diferença entre um for e um foreach quando se precisa iterar uma array pode ser uma questão que tanto irá fortalecer o conhecimento dos membros que já sabem a diferença na tentativa de explicar, quanto irá fazer com o que o grupo tenha um conteudo bastante explicativo e detalhado. Papel que claramente a documentação do php faz. Mas como na própria documentação, existem vários exemplos e contribuições de usuários que utilizam apetrechos pra cada funcionalidade.
Resumindo, acredito que debates poderiam ser mais explorados. Refatoração, compreensão de funcionalidades, bibliotecas externas e etc.
Seria uma contribuição/agregação/implementação interessante ao grupo.

**Comment by kinncj** [comment]
Olá @Soufraz, temos uma issue parecida: https://github.com/php-brasil/Documentos/issues/4

Ela se encaixa na sua dúvida? gostaria de adicionar algo? Ela ainda esta aberta para votação!

ping @netojoaobatista

**Comment by Soufraz** [comment]
Beleza João! Serve sim. Ótimo..
