### ISSUE TITLE
Votos válidos

### ISSUE THREAD

**Issue by augustohp** [php-brasil/Documentos#14]
Acho válido conversamos a respeito do que são: um voto, uma votação e seus resultados.

Nem sempre estaremos aí para o grupo, o interessante é que ele sobreviva a uma ecatombe nuclear, nossa trágica morte  ou ausência. Acho interessante maximizar a participação de todos.
Se pensarmos em mecânicas simples, mas que automaticamente eliminem ruídos de participação acho que encontraremos um bom balanço a tudo.

**Comment by augustohp** [comment]
Sou a favor do seguintes conceitos:
- **Voto**: Valor `booleano`, sim ou não.
- **Votação**: 
  - Local? GitHub. É mais fácil manter perfis fakes no Facebook do que no GitHub.
  - Quem pode iniciar? Todos.
  - Tipos:
    - Solicitação de cancelamento do ban em troca de ações construtivas. (Duração 1 semana)
    - Mudança nas regras. (Duração 3 meses)
    - Mudança nas configurações do grupo no GitHub ou no Facebook. (Duração 3 meses)
- **Resultados**:
  - Votações menos longas que 1 mês: 50% dos votos +1.
  - Votações mais longas que 1 mês: 2/3 dos votos.

**Comment by henriquemoody** [comment]
:+1: 

Eu só adicionaria peso aos votos no caso voto de moderador (como você) teria mais peso do que voto de usuário (como eu). Pra mim faz sentido já que, independente da decisão, vocês são os responsáveis pelo grupo.

**Comment by kinncj** [comment]
_Apenas um adendo_
- Resultados:
  - Votações menos longas que 1 mês: 50.1% dos votos +1.

A vantagem de manter a votação por aqui, como o @augustohp citou, são os fake profiles.
A desvantagem, é que a grande maioria da nossa base de usuários, tendo como base os posts que vejo e nomes que procurei por aqui, não possuem acesso ao GitHub.

Com relação ao _peso_ dos votos, concordo que os votos devam ter um peso, já não sei como mensurar qual e o motivo de um voto pesar mais que o outro... acredito que usuários mais dentro das normas e ativos devam ter mais pesos... por que dentro das normas junto com ativo? pelo simples motivo de que o mais ativo, pode ser o mais fora das regras também.

**Comment by jackmakiyama** [comment]
:+1:

Creio que deve manter aqui, aqui também seria um bom lugar para um "banido" abrir uma issue e discutir o por que e como reparar, claro que eles querem xingar na maioria das vezes e não resolver... =/

Acho que voto é booleano e pronto, sem favorecer ninguém. Se for algo que esteja interferindo no grupo podemos abrir uma discussão invés de votação, assim chegando em um consenso.

**Comment by augustohp** [comment]
> Eu só adicionaria peso aos votos no caso voto de moderador (como você) teria mais peso do que voto de usuário (como eu). Pra mim faz sentido já que, independente da decisão, vocês são os responsáveis pelo grupo.

Eu posso concordar com peso em votos, mas não acho que títulos devem ser considerados como peso, eles são arbitrários demais.
Consideraria o peso em termos de contribuição pra comunidade, exemplos que eu consigo pensar agora:
- Contribuição em projetos com bastante atividade (commit) e download no [Packagist](https://packagist.org/).
- Interação (comentário, voto válido) nas votações anteriores.

Fora isso, me incomoda favorecer membros mais antigos que recentemente não são tão produtivos quanto os novos. Acho importante favorecer membros novos com vontade de melhor, ajudar e participar da comunidade.

Acho mais importante ainda valorizar o produto do trabalho da comunidade: código. Encontros são importantes? São. O networking é importante? É. Melhorar nosso mercado de trabalho é importante? Com certeza.
Mas sem um artigo mensurável  -e tangível, visível - que sobreviva às empresas, o afastamento de membros e a filosofia do software livre acho que, com o tempo, perdemos mais do que ganhamos.

> Apenas um adendo
> 
> ```
> Resultados:
>     Votações menos longas que 1 mês: 50.1% dos votos +1.
> ```

Pra fazer algo que sobreviva bastante tempo (~5, 10, 20 anos), acho importante permitir a participação de todos os interessados.
Existe o argumento de que quem ta interessado, vai participar numa votação que dure 1 mês ou menos, mas minha preocupação é com os votos e os imprevistos da vida.
Acho essencial considerar a posição de todos como voluntária. A gente vai interagir no nosso tempo livre. Quando possível.
Com um tempo bem longo pra mudanças consideráveis, acho que da pra deixar os pontos bem claros de cada um. Da tempo das pessoas reconsiderarem os votos e ter uma mudança mais positiva.
E 1 mês na vida de uma pessoa, pode acontecer bastante coisa, dar tempo pra inclusão das pessoas independente da situacão da vida dela, acho que vai agregar mais do que prejudicar.
Como grupo, não precisamos tomar decisões rápidas, o que temos hoje funciona e vai continuar funcionando.

> A desvantagem, é que a grande maioria da nossa base de usuários, tendo como base os posts que vejo e nomes que procurei por aqui, não possuem acesso ao GitHub.

"Não possuem acesso ao GitHub" significa o quê exatamente? Eu vejo os seguintes problemas:
1. Não tem conta: O acesso às discussões é público. Criar uma conta é gratuito e sem buracracia nenhuma.
2. Tem mais gente no Facebook que no [GitHub](https://github.com/): Sem dúvida, mas a rede social de desenvolvimento é o [GitHub](https://github.com/). O que produzimos de software e discussões acerca estão aqui. Pra um fórum, [isso](https://github.com/) é uma merda; mas se o documento de regras/estatuto/votação for um arquivo... a gente consegue ter o histórico das alterações, linkar issues no commit, ter várias assinaturas dentro de um mesmo commit... enfim: uma coisa FODA.
3. O manolo vai precisar aprender a usar o Git: Isso é ruim?!

**Comment by henriquemoody** [comment]
Eu sugeri o peso maior para administradores porque:
1. Faz sentido pra mim que moderadores possuam mais peso: Não é qualquer um que é moderador uma vez que os mesmos são responsáveis pela saúde do grupo nada mais justo do que eles possuírem um peso maior.
2. Nem todo mundo sabe o que é melhor pra si mesmo, quanto mais para um grupo com quase 9 mil membros
3. É mais fácil diferenciar: Se utilizarmos meritocracia para dar o peso, seja pela participação no grupo ou pelos projetos que se contribui teríamos que utilizar/criar alguma ferramenta para isso. Talvez utilizar a [API](https://api.github.com/users/henriquemoody/events) do GitHub possa ser de valia, mas como interpretar os dados e dar peso, além de lidar com o tempo da votação pode ser complicado, sem contar que eu _acho_ que não existe algo assim no Facebook.

Sobre as votações serem no GitHub, estou de completo acordo por todos os motivos que já foram citados. Na realidade os participantes nem precisam aprender Git para isso, apenas utilizar o sistema de issues e tendo em vista os objetivos que o grupo possui incentivar o uso dessa ferramenta (assim como o Git em si) é algo ótimo.

**Comment by augustohp** [comment]
Sugeri uma PR em #17.
