### ISSUE TITLE
Adendo às Regras relacionadas com publicidade e divulgações

### ISSUE THREAD

**Issue by leocavalcante** [php-brasil/Documentos#16]
Adendo ao inciso 5 do parágrafo _Regras relacionadas com publicidade e divulgações_:

> [x] Permitimos a divulgação de cursos e eventos, gratuitos ou pagos, se estiverem relacionados com PHP, **exceto conteúdo de carácter publicitário e/ou auto-promocional**;

**Comment by kinncj** [comment]
:+1:

**Comment by augustohp** [comment]
:+1: As-is.

Mas sou a favor acrescentar que pra divulgar coisas "pagas" é preciso ter alguma vantagem **exclusiva** pro grupo. Cupom de desconto, sorteio, etc.

**Comment by lcobucci** [comment]
:+1:

A sugestão do @augustohp é extremamente válida

**Comment by nelsonsar** [comment]
:+1:

**Comment by ogabrielsantos** [comment]
:thumbsup:

+1 pra sugestão do @augustohp

**Comment by danielarcher** [comment]
:thumbsup:

**Comment by iannsp** [comment]
+1

**Comment by renatomefi** [comment]
Entendo a necessidade, porém há uma dicotomia ao dizer que é permitido postar algo pago e não publicitário ao mesmo tempo. 
Quanto às duplas interpretações elas existem tanto no âmbito dos usuários quanto dos administradores, vide o último tópico de discussão.

**Comment by beeblebrox3** [comment]
Concordo com o Renato e acho que a sugestão do Augusto com a regra como está atualmente é uma boa opção, uma vez que pode mesmo gerar confusão definir se post é ou não publicidade.

**Comment by leocavalcante** [comment]
Num sentido estrito, publicidade é essencialmente comercial, mas o termo pode ser estendido para uma interpretação ampla onde tornar público é publicidade. Será que a gente encontra um adjetivo 
que evita ambiguidades?
Quanto as duplas interpretações, sempre irão existir, não é uma ciência exata, se na nossa própria jurisdição nenhuma lei esta livre de ambiguidade, quiçá as regras dum grupo no Facebook, estamos sujeitos a interpretação dos administradores, por isso a ideia é tentar deixar o mais claro possível.

**Comment by augustohp** [comment]
Conteúdo livre. Assim como código. O problema é que esse termo no nosso contexto implica numa licença livre ou creative commons. Grátis não é livre. Prefiro o conteúdo livre, sem intermédio nem condições mas sou consciente das restrições disso.

**Comment by ivanrosolen** [comment]
:thumbsup:
+1 pra sugestão do @augustohp

**Comment by henriquemoody** [comment]
> Permitimos a divulgação de cursos e eventos, gratuitos ou pagos, se estiverem relacionados com PHP**, desde que não possuam caráter auto-promocional e que, quando pagos, apresentem vantagens exclusivas para o grupo**.

O que acham disso?

**Comment by augustohp** [comment]
+1 Moody

**Comment by netojoaobatista** [comment]
Minha sugestão:
- Permitimos a divulgação de cursos e eventos relacionados com PHP, gratuitos ou pagos, desde que sigam os seguintes critérios:
  1. Eventos gratuitos, presencial ou online.
  2. Cursos gratuitos, desde que possuam uma licença livre. Ex: Creative Commons.
  3. Cursos e eventos pagos, **mediante aprovação expressa dos administradores**, desde que haja uma vantagem para **todo** o grupo. Ex: Desconto, cortesias, etc.

**Comment by ogabrielsantos** [comment]
:+1: @netojoaobatista

**Comment by ogabrielsantos** [comment]
Esse "mediante aprovação expressa dos administradores" vai dificultar um membro qualquer de identificar anomalias e ajudar a administração, não?

**Comment by henriquemoody** [comment]
Concordo com o @ogabrielsantos, acho que, desde que apresente vantagens **exclusivas** para o grupo pode ser postado sem aviso prévio.

Também acho que deveria ser incluído a questão da auto-promoção visto que, segundo algumas pessoas com as quais conversei, isso é também algo que incomoda.

**Comment by netojoaobatista** [comment]
Update, @henriquemoody:
- Permitimos a divulgação de cursos e eventos relacionados com PHP, gratuitos ou pagos, desde que **não possuam caráter autopromocional** e sigam os seguintes critérios:
  1. Eventos gratuitos - presencial ou online.
  2. Cursos gratuitos - desde que possuam uma licença livre. Ex: Creative Commons.
  3. Cursos e eventos pagos - **mediante aprovação expressa dos administradores**, desde que haja uma vantagem para **todo** o grupo. Ex: Desconto, cortesias, etc.

**Comment by luismilanese** [comment]
(Y)

**Comment by luismilanese** [comment]
:+1:

**Comment by netojoaobatista** [comment]
O **mediante aprovação expressa dos administradores** é importante porque transfere a decisão de aprovação desse tipo de coisa para os administradores. Assim, os admins podem negociar as _vantagens_ para o grupo antes de permitir a postagem.

**Comment by vinicius-ianni** [comment]
Ficou bom assim, bem claro e evita interpretações enviesadas das regras

**Comment by henriquemoody** [comment]
Entendi seu ponto, @netojoaobatista.

Porém, se tratando de **cursos**, sou a favor de conteúdo gratuito, mesmo que possuam uma licença mais restrita.

**Comment by netojoaobatista** [comment]
Podemos remover a questão da licença, @henriquemoody. Mesmo porque às vezes o cara publica o conteúdo sem qualquer licença. Novo update:
- Permitimos a divulgação de cursos e eventos relacionados com PHP, gratuitos ou pagos, desde que **não possuam caráter autopromocional** e sigam os seguintes critérios:
  1. Cursos e eventos gratuitos - permitidos tanto presenciais quanto online.
  2. Cursos e eventos pagos - apenas **mediante aprovação expressa dos administradores**, desde que haja uma vantagem para **todo** o grupo. Ex: Desconto, cortesias, etc.

**Comment by henriquemoody** [comment]
:point_up: :+1:

**Comment by lcobucci** [comment]
:+1: @netojoaobatista 

Isso faz com que eventos como PHP Experience, PHP Conference Brasil, PHPSC Conference, TDC e tantos outros eventos ofereçam algo à comunidade em troca da divulgação.

**Comment by ogabrielsantos** [comment]
:+1: @netojoaobatista

**Comment by netojoaobatista** [comment]
> Isso faz com que eventos como PHP Experience, PHP Conference Brasil, PHPSC Conference, TDC e tantos outros eventos ofereçam algo à comunidade em troca da divulgação.

Correto, @lcobucci!

## Regras relacionadas com publicidade e divulgações

Seguindo a sugestão do @leocavalcante:

> Adendo ao inciso 5 do parágrafo Regras relacionadas com publicidade e divulgações:

**Texto em votação**
- Permitimos a divulgação de cursos e eventos relacionados com PHP, gratuitos ou pagos, **desde que não possuam caráter autopromocional** e sigam os seguintes critérios:
  1. Cursos e eventos gratuitos - permitidos tanto presenciais quanto online.
  2. Cursos e eventos pagos - apenas **mediante aprovação expressa dos administradores**, desde que haja uma vantagem para o grupo. Ex: Desconto, cortesias, etc.

| Nome | Sim | Não |
| --- | --- | --- |
| @netojoaobatista | :+1: |  |
| @henriquemoody | :+1: |  |
| @lcobucci | :+1: |  |
| @ogabrielsantos | :+1: |  |
| @beeblebrox3 | :+1: |  |
| @ivanrosolen | :+1: |  |
| @cfermino | :+1: |  |
| @iannsp | :+1: |  |
| @lucas-cdsilva | :+1: |  |
| @augustohp | :+1: |  |
| @vinicius-ianni | :+1: |  |
| @wesleyvicthor | :+1: |  |
| @brunogasparetto | :+1: |  |
| @caferrari | :+1: |  |
| @danielcramer | :+1: |  |
| @giovanisilveira | :+1: |  |
| @leocavalcante | :+1: |  |
| @GabrielJMJ | :+1: |  |
| @drgomesp | :+1: |  |
| @netohunter | :+1: |  |
| @kinncj | :+1: |  |
| @nelsonsar |  |  |
| @luismilanese |  |  |
| **Total** | 21 | 0 |

**Comment by beeblebrox3** [comment]
:+1: @netojoaobatista

**Comment by henriquemoody** [comment]
Só pra que fique claro: a diferença entre **todo** e **exclusivo** é gritante, pois **exclusivo** pode ser para o **todo** ou não, mas **todo** pode não ser **exclusivo**.

Eu concordo com o **todo** apenas porque, nestes casos, é necessário a **aprovação expressa dos administradores**, mas também concordo se isso não for específicado.

**Comment by netojoaobatista** [comment]
Você está correto, @henriquemoody. Eu removi o termo _todo_ do texto. Como a decisão final é dos administradores, eles poderão negociar o _todo_, _exclusivo_, etc

**Comment by ivanrosolen** [comment]
+1

**Comment by cfermino** [comment]
+1

**Comment by iannsp** [comment]
+1

**Comment by augustohp** [comment]
+1

**Comment by lucascdsilva** [comment]
(Y) +1
Mas como vai funcionar "aprovação expressa dos administradores." ? Issue?  Inbox no facebook?

**Comment by netojoaobatista** [comment]
Nesse caso, @lucas-cdsilva, se o texto for aprovado, colocarei um asterisco dizendo para entrar em contato inbox ou através da página do [PHP Brasil](https://www.facebook.com/tambem.nao.tem.biscoito).

**Comment by vinicius-ianni** [comment]
+1

**Comment by wesleyvicthor** [comment]
:+1:

**Comment by alexandretaz** [comment]
Duas propostas de adendo:
1-) Definir o que é autopromoção, se o critério for subjetivo fica foda
2-)Cursos e eventos pagos - apenas mediante aprovação expressa dos administradores, desde que haja uma vantagem para **todos os membros do grupo**. Ex: Desconto, cortesias, etc.

**Comment by henriquemoody** [comment]
Sobre o que o @alexandretaz falou:

+1 para 1
-1 para 2

Nem sempre TODOS os membros podem se beneficiar. Acho válido se um evento, com um valor de ingresso mais alto, oferecer um número limitado de descontos pro grupo, por exemplo.

**Comment by alexandretaz** [comment]
@henriquemoody  o 2 não é que todos possam usar a vantagem, mas que seja oferecido a todos, tipo um voucher para as 10 primeiras inscrições, todo mundotem acesso, e o numero da oferta é limitado, mas estava disponível para todos

**Comment by brunogasparetto** [comment]
@netojoaobatista  :+1: para o texto final

**Comment by caferrari** [comment]
+1

**Comment by netojoaobatista** [comment]
@alexandretaz,

> 1-) Definir o que é autopromoção, se o critério for subjetivo fica foda

Publicações em que fique claro o propósito do autor se autopromover. Por exemplo, propaganda de blogs pessoais.

> 2-)Cursos e eventos pagos - apenas mediante aprovação expressa dos administradores, desde que  haja uma vantagem para todos os membros do grupo. Ex: Desconto, cortesias, etc.

O _mediante aprovação expressa dos administradores_ é para que formatos e propostas possam ser analisados. Os administradores sempre procurarão o melhor para todo o grupo.

**Comment by danielarcher** [comment]
+1

**Comment by giovanisilveira** [comment]
+1

**Comment by leocavalcante** [comment]
:+1: @netojoaobatista

**Comment by gabrieljmj** [comment]
+1 @netojoaobatista

**Comment by drgomesp** [comment]
:+1:

**Comment by aneto88** [comment]
+1

**Comment by netojoaobatista** [comment]
Adendo votado, aprovado e mesclado às regras.
