### ISSUE TITLE
Grupo de contribuidores

### ISSUE THREAD

**Issue by augustohp** [php-brasil/Documentos#18]
Podemos manter um grupo no Github de colaboradores com todo mundo que já contribuiu com um voto. Podemos criar um processo formal de linkar um perfil do GitHub com o do Facebook, membro do grupo.

Com isso, limamos a lista de colaboradores das regras e temos uma lista sempre atualizada. Além de um atalho para usar e informar antigos contribuidores de alterações.

**Comment by henriquemoody** [comment]
:+1:, utilizando uma team específica pra isso, presumo eu.

**Comment by augustohp** [comment]
> :+1:, utilizando uma team específica pra isso, presumo eu.

Exato, ela já existe.

**Comment by iannsp** [comment]
nao vejo problema algum
:+1:

**Comment by henriquemoody** [comment]
O grupo já estava criado, apenas adicionei os usuários: @php-brasil/contribuidores
