### ISSUE TITLE
Projetos open-source da comunidade

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#21]
# Resultado final da votação

| Projeto | Autor | Utilidade | Técnica | Originalidade | Total |
| --- | --- | --- | --- | --- | --- |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 171 | 102 | 23 | 296 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 165 | 82 | 34 | 281 |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 123 | 64 | 47 | 234 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 126 | 46 | 33 | 205 |
## Critérios

| Projeto | Autor | Utilidade | Técnica | Originalidade | Total |
| --- | --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira |  |  |  |  |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan |  |  |  |  |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch |  |  |  |  |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord |  |  |  |  |

A tabela acima lista os projetos participantes e os quesitos que serão analisados.
1. Utilidade tem peso **3** - O total de pontos será multiplicado por 3
   - Utilidade é o aspecto mais importante de um projeto open-source. É sua utilidade que fará com que o projeto seja utilizado, melhorado e evolua para estar sempre atendendo as necessidades da comunidade.
2. Técnica tem peso **2** - O total de pontos será multiplicado por 2
   - A técnica é relevante, pois ela afeta a utilização de um projeto. Mas é menos relevante que sua utilidade porque, se o projeto for realmente útil, a própria comunidade se unirá para resolver os déficits técnicos.
3. Originalidade tem peso **1** - O total de pontos será igual ao recebido
   - A originalidade é o menos relevante, porque se uma ideia for realmente útil e tecnicamente bem implementada, não importa muito se já tivermos _n_ outros projetos que resolvam o mesmo problema. Talvez uma nova implementação da mesma ideia simplesmente consiga resolver o problema de uma forma melhor.
## Votação

A votação será pública, com a colaboração da própria comunidade. E será pública porque, se o projeto é open-source, então ele é feito para a comunidade. Nada mais justo que a própria comunidade possa participar da avaliação de um projeto.

Cada membro que votar, irá pontuar cada quesito entre 0 e 5. Por exemplo:

| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| Projeto X | Fulano | 4 | 4 | 1 |
| Projeto Y | Beltrano | 3 | 5 | 2 |
| Projeto Z | Cicrano | 5 | 2 | 3 |

Ao final da votação, multiplicaremos as pontuações conforme descrito anteriormente e, então, teremos o resultado final.
## Template para tabela de votação

``` markdown
Projeto|Autor|Utilidade|Técnica|Originalidade
-------|-----|---------|-------|-------------
[DateTime](https://github.com/project-melody/datetime)|@leviferreira|x|y|z
[Economizer](https://github.com/gugoan/economizzer)|@gugoan|x|y|z
[DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module)|@gabrielsch|x|y|z
[Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher)|@danizord|x|y|z
```

**Comment by kinncj** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 1 | 2 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 4 | 1 | 4 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 3 | 1 |

**Comment by netojoaobatista** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 1 | 2 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 3 | 1 |

**Comment by drgomesp** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 1 | 1 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 3 | 1 |

**Comment by giopetris** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 1 | 1 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 1 | 1 | 1 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 5 | 5 | 4 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 5 | 5 | 2 |

**Comment by iannsp** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 1 | 1 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 1 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 2 | 1 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 1 |

**Comment by henriquemoody** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 2 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 1 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 2 | 1 |

**Comment by ivanrosolen** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 1 | 2 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 1 |

**Comment by daniej23** [comment]
Projeto	                            Autor	          Utilidade	    Técnica	Originalidade
DateTime                        @leviferreira	       5	          4	                4
Economizer                     @gugoan	               3	          4	                2
DoctrineMoneyModule    @gabrielsch	       4	          3	                2
Squid\EventDispatcher    @danizord              3                 2                    3

**Comment by daniej23** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 5 | 4 | 4 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 3 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 2 | 3 |

**Comment by gabrielsch** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 1 | 2 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 2 | 2 | 3 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 3 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 4 | 2 |

**Comment by leviferreira** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 4 | 3 | 5 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 2 | 2 | 1 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 3 | 3 | 2 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 3 | 1 |

**Comment by danizord** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 3 | 4 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 2 | 3 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 4 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 4 | 1 |

**Comment by oandre** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 3 | 2 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 2 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 2 | 1 | 1 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 2 |

**Comment by guilhermeturri** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 4 | 2 | 4 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 2 | 3 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 1 | 1 | 1 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 2 |

**Comment by valentim** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 3 | 3 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 2 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 2 | 1 | 1 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 1 |

**Comment by andreyvital** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 2 | 3 | 4 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 3 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 4 | 3 | 4 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 4 | 4 | 1 |

**Comment by raphaelsaez** [comment]
| Projeto | Autor | Utilidade | Técnica | Originalidade |
| --- | --- | --- | --- | --- |
| [DateTime](https://github.com/project-melody/datetime) | @leviferreira | 4 | 2 | 3 |
| [Economizer](https://github.com/gugoan/economizzer) | @gugoan | 3 | 1 | 2 |
| [DoctrineMoneyModule](https://github.com/zfbrasil/doctrine-money-module) | @gabrielsch | 2 | 1 | 1 |
| [Squid\EventDispatcher](https://github.com/squidfacil/event-dispatcher) | @danizord | 3 | 3 | 2 |
