### ISSUE TITLE
Adendo à seção das regras sobre publicidade e divulgações

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#24]
# Sugestão

Temos visto, com uma certa recorrência, a publicação e divulgação de pesquisas no grupo. Muitas dessas pesquisas estão diretamente relacionadas com nosso escopo, mas não trazem benefício algum para o grupo como um todo. Para tentar utilizar a pesquisa como meio para fomentar uma discussão sobre o tema pesquisado, proponho o seguinte adendo:
## Regras relacionadas com publicidade e divulgações
- [x] Permitimos a divulgação de pesquisas no grupo, acadêmicas ou não, desde que sigam os seguintes critérios: 
  1. Esteja dentro do escopo do grupo.
  2. Que o resultado da pesquisa seja público, ou seja, o autor se compromete a publicar o resultado final da pesquisa.

Acho que a divulgação do resultado da pesquisa é interessante pois promove uma discussão sobre fatos constatados durante a pesquisa. Os dados quantitativos permitem uma análise qualitativa dos resultados da pesquisa.

**Comment by iannsp** [comment]
prefiro mudar uma coisa:
 resultado da pesquisa deve ser publico desde o inicio da pesquisa.
google forms fornece isso.

**Comment by netojoaobatista** [comment]
Perfeito, @iannsp! Eu não sabia que o GForms oferecia esse recurso!

# Atualização

## Regras relacionadas com publicidade e divulgações
- [x] Permitimos a divulgação de pesquisas no grupo, acadêmicas ou não, desde que sigam os seguintes critérios: 
  1. Esteja dentro do escopo do grupo.
  2. Que o resultado da pesquisa seja público desde o início, ou seja, o autor/pesquisador/responsável pela pesquisa se compromete a manter os resultados parciais e totais abertos para consulta pública.

**Comment by henriquemoody** [comment]
:+1:

**Comment by kinncj** [comment]
:+1:

**Comment by ferminodev** [comment]
:+1:

**Comment by gabrieljmj** [comment]
:+1:

**Comment by iannsp** [comment]
:+1:

**Comment by joaorodriguesjr** [comment]
:+1:

**Comment by ivanrosolen** [comment]
:+1:
