### ISSUE TITLE
Lazy Consensus em votações

### ISSUE THREAD

**Issue by henriquemoody** [php-brasil/Documentos#25]
Afim de tornar nossa comunidade mais ágil seria interessante adotarmos oficialmente o conceito de [Lazy Consensus](https://rave.apache.org/docs/governance/lazyConsensus.html) nos nossos processos de votação mas mantermos o prazo de 1 semana para as propostas, ao invés de 72 horas.
## 

| Usuário | :+1: | :-1: |
| --- | --- | --- |
| @henriquemoody | :white_check_mark: |  |
| @augustohp | :white_check_mark: |  |
| @netojoaobatista | :white_check_mark: |  |
| @ferminodev | :white_check_mark: |  |
| @iannsp | :white_check_mark: |  |
| @ivanrosolen | :white_check_mark: |  |
| @kinncj | :white_check_mark: |  |
| @GabrielJMJ | :white_check_mark: |  |
| @KennedyTedesco | :white_check_mark: |  |
|  | 9 | 0 |

**Comment by augustohp** [comment]
:+1:

**Comment by netojoaobatista** [comment]
Isso é quase ditatorial. Mas eu gosto.

:+1:

**Comment by ferminodev** [comment]
:+1:

**Comment by iannsp** [comment]
:+1: 
sou fã disso ai :)

**Comment by ivanrosolen** [comment]
:+1:

**Comment by kinncj** [comment]
:+1:

**Comment by gabrieljmj** [comment]
:+1:

**Comment by ferminodev** [comment]
:+1:

**Comment by KennedyTedesco** [comment]
:+1:

**Comment by lucascdsilva** [comment]
:+1: :grinning:

**Comment by henriquemoody** [comment]
A decisão já foi tomada, agora é preciso atualizar o site, mas acho que podemos fechar essa issue.
