### ISSUE TITLE
Desabilitar redirecionamento do Github pages

### ISSUE THREAD

**Issue by leocavalcante** [php-brasil/Documentos#30]
Não faço ideia do porquê (que tipo de configuração faz isso), mas php-brasil.github.io redireciona pra phpbr.org, porém esse domínio está expirado. Minha sugestão é usar o subdomínio do Github mesmo, não vejo sentido em pagar um domínio pra isso.

**Comment by ogabrielsantos** [comment]
+1

**Comment by leocavalcante** [comment]
Ah, achei quem faz o redirect :stuck_out_tongue: 
https://github.com/php-brasil/php-brasil.github.io

**Comment by giovannipds** [comment]
:+1:
