### ISSUE TITLE
Questões relacionadas com divulgações

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#5]
Quais dos seguintes casos devemos permitir divulgação no grupo?
1. de empresas
2. páginas do Facebook
3. páginas pessoais, portfolio, etc
4. eventos **pagos**, cursos pagos, etc
5. eventos **gratuitos**, hangouts, cursos online gratuitos, etc
6. vagas de trabalho fixo, temporário ou freelances.
7. de open source relacionado com PHP, como bibliotecas, frameworks, etc.
## 
#### Votação

| Usuário | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| @brunoew | :-1: | :-1: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @henriquemoody | :wave: | :wave: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @kinncj | :wave: | :wave: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @marcker | :-1: | :-1: | :-1: | :+1: | :+1: | :wave: | :+1: |
| @rogerioadris | :-1: | :-1: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @VitorArjol | :-1: | :-1: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @Zizaco | :-1: | :-1: | :-1: | :+1: | :+1: | :-1: | :+1: |
| @lUCAS-CDSILVA | :-1: | :-1: | :-1: | :+1: | :+1: | :-1: | :+1: |

**Comment by vitorarjol** [comment]
Concordo com a divulgação de: 4, 5 e 7.
Compartilhar páginas de empresas (1), ou outras páginas do facebook (2) só vai gerar um flood no grupo.
E para vagas de trabalho (6) existem páginas/sites específicos para isso, acredito que foge do contexto do grupo.

**Comment by vsouza** [comment]
Acho que a 5 deveria estar liberada, desde que não tenha posts repetidos. A opção 7 também deveria ficar liberada.

**Comment by skvggor** [comment]
4 até 7 - por tratar-se de assuntos relacionados ao PHP, mesmo que de forma indireta.
Cogito ainda, que a 6 (sobre vagas) deve-se moderar com cuidado para não haver excessos por parte do autor.

**Comment by brunoew** [comment]
Voto nas opções 4, 5 e 7. 
Vagas poderiam ser anunciadas em outro grupo com esta finalidade (não verifiquei se já existe).
As demais opções irão floodar sem trazer benefícios para a comunidade como um todo.

**Comment by vsouza** [comment]
brunoew, existem sim vários grupos pra isso. Concordo com você, acho que seria melhor deixar com os grupos destinados á isso.

**Comment by rogerioadris** [comment]
Concordo com a divulgação 4, 5 e 7

**Comment by kinncj** [comment]
- eventos gratuitos, hangouts, cursos online gratuitos, etc
- de open source relacionado com PHP, como bibliotecas, frameworks, etc.

Apenas se tiver retorno à comunidade, como apoio ou algo do tipo:
- de empresas
- eventos pagos, cursos pagos, etc

**Comment by renatomefi** [comment]
Acredito que o 3 também poderia ser liberado desde que seguindo as regras sobre os assuntos, poderíamos entender sinippets e outros projetos também como entradas de blogs, o que muda é a forma de comunicar.

**Comment by kinncj** [comment]
@renatomefidf , o item 3 se refere à auto-promoção

**Comment by brayann** [comment]
Se a 5 for liberada, liberem todo tipo de conteúdo que envolva PHP. Uma vez postamos lá um Hangout sobre Laravel, e o post foi excluído sem nem aviso prévio. Que eu saiba ele foi escrito com PHP :)
Sei que os mods são meio haters do laravel, mas podem ter pessoas que gostem.

**Comment by netojoaobatista** [comment]
Se o item 5 for liberado, @brayann, valerá para todo conteúdo PHP organizado pelas diversas comunidades existentes. Se não for liberado, mesmo os hangouts sobre OOD, serão proibidos.

A regra valerá para todos.

**Comment by Zizaco** [comment]
4, 5 e 7 :+1:

**Comment by henriquemoody** [comment]
> 3 - páginas pessoais, portfolio, etc
> 6 - vagas de trabalho fixo, temporário ou freelances.

:-1:

> 1 - de empresas
> 2 - páginas do Facebook

:wave: Se forem parceiros do grupo

> 4 - eventos **pagos**, cursos pagos, etc
> 5 - eventos **gratuitos**, hangouts, cursos online gratuitos, etc
> 7 - de open source relacionado com PHP, como bibliotecas, frameworks, etc.

:+1: Sem flood, ou up.

**Comment by lucascdsilva** [comment]
4, 5 e 7.

**Comment by brunogasparetto** [comment]
4, 5 e 7.

Item 3 abriria exceção somente para algum artigo que algum membro escreveu e resolveu compartilhar, mas com atenção pra evitar flood de posts do usuário anunciando a sua página.

**Comment by renatomefi** [comment]
4, 5 e 7

Apoio a mesma ressalva do @brunogasparetto

**Comment by ogunhe** [comment]
Somente 4, 5 e 7

**Comment by jackmakiyama** [comment]
> de empresas
> páginas do Facebook
> páginas pessoais, portfolio, etc
> vagas de trabalho fixo, temporário ou freelances.

:-1:
Creio que esses só devem ser postados por um administrador.

> eventos pagos, cursos pagos, etc

:wave:
Eventos de PHP pagos sim.
Cursos pagos não.

> eventos gratuitos, hangouts, cursos online gratuitos, etc
> de open source relacionado com PHP, como bibliotecas, frameworks, etc.

:+1:

Todos sem flood.

Lembrando que existe a area de eventos no grupo, por mim qualquer evento deve ser colocado lá.

**Comment by MaurilioNovais** [comment]
Acredito que `4`, `5` e `7` estão de acordo :+1:

**Comment by yanmagale** [comment]
4,5 e 7.

**Comment by filipiarruda** [comment]
Do 4 ao 7 é válido, está relacionado com PHP, pois projetos open source, ajudam o próprio grupo a se desenvolver mais, incentiva os membros a buscar mais conhecimento, cursos, palestrar e hungouts complementam o objetivo do grupo, que é compartilhar conhecimento. E por último, vagas de freela ou fixo, são importantes, pois quem está no grupo está sempre atendo a oportunidades na área. O grupo se torna assim uma referência no assunto.

**Comment by walkeralencar** [comment]
Contra: 1,2,3 e 6
A favor: 4,5 e 7
