### ISSUE TITLE
Questões relacionadas com o idioma

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#6]
Quais idiomas devemos permitir que as postagens sejam feitas no grupo?
1. Apenas português
2. Português ou inglês
3. Qualquer idioma
## 
#### Votação

| Usuário | 1 | 2 | 3 |
| --- | --- | --- | --- |
| @drgomesp | :+1: | :-1: | :-1: |
| @GabrielJMJ | :+1: | :-1: | :-1: |
| @henriquemoody | :+1: | :-1: | :-1: |
| @kinncj | :+1: | :-1: | :-1: |
| @marcker | :+1: | :-1: | :-1: |
| @rogerioadris | :+1: | :-1: | :-1: |
| @sergiors | :+1: | :-1: | :-1: |
| @lUCAS-CDSILVA | :+1: | :-1: | :-1: |

**Comment by sergiors** [comment]
> Apenas português

Não há motivo para discutir em inglês rs, inglês apenas se for para referência.

**Comment by gabrieljmj** [comment]
Não vejo o porquê do inglês sendo que o grupo é destinado apenas para brasilieiros (PHP **Brasil**), então opção **1**.

**Comment by skvggor** [comment]
Penso que, nem sempre haverá conteúdo em Português sobre algum assunto (mais "avançado"), o que não nos impede de discutirmos em português um texto em outro idioma.

**Comment by rogerioadris** [comment]
Apenas Português

**Comment by kinncj** [comment]
PHP Brasil... PT-BR

**Comment by drgomesp** [comment]
Apenas PT-BR

**Comment by henriquemoody** [comment]
:+1: HUEHUE

**Comment by lucascdsilva** [comment]
1

**Comment by brunogasparetto** [comment]
Somente pt-br

**Comment by ogunhe** [comment]
Somente pt-br

**Comment by jackmakiyama** [comment]
Somente PT-BR
