### ISSUE TITLE
Questões relacionadas com o conteúdo da postagem

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#7]
Quais os tipos de conteúdos devemos permitir?
1. Postagem de arquivos **diretamente** no grupo.
2. Postagem de arquivos somente através de links.
3. Postagem de imagens **diretamente** no grupo.
4. Postagem de imagens somente através de links.
5. Postagem de código **diretamente** no grupo.
6. Postagem de código apenas através de links. (Github, pastebin, etc).
7. Texto **TODO EM CAIXA ALTA**.
8. Caixa alta apenas em casos muito específicos, para dar ênfase em algum termo, utilizado na menor quantidade possível.
9. Caixa alta sob hipótese alguma.
## 
#### Votação

| Usuário | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| @brunoew | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: |
| @henriquemoody | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: |
| @kinncj | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: |
| @rogerioadris | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: |
| @lUCAS-CDSILVA | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: | :+1: | :-1: |

**Comment by rogerioadris** [comment]
Concordo com 2, 4, 6 e 8 para não ficar muito poluído o grupo. (um ponto contra seria a pessoa deletar este conteúdo depois de solucionado, seria bom manter para ajudar outras pessoas com a mesma duvida ou duvida parecida)

**Comment by kinncj** [comment]
2,4,6,8... netiqueta.

**Comment by brunoew** [comment]
2,4,6 e 8

**Comment by henriquemoody** [comment]
:+1: 2,4,6 e 8

**Comment by lucascdsilva** [comment]
2,4,6,8

**Comment by brunogasparetto** [comment]
4, 6 e 8 - sim (permitir código e imagens somente por links, afinal é muito melhor visualmente) e caixa-alta só com muita moderação (o que elimina o item 9 de proibir sempre).

Todos os outros itens proibidos :)

**Comment by ogunhe** [comment]
1 NÃO
2 SIM
3 SIM
4 NÃO
5 NÃO
6 SIM
7 NÃO
8 SIM
9 NÃO

**Comment by jackmakiyama** [comment]
1. :-1:
2. :+1:
3. :-1:
4.  :+1:
5. :-1:
6. :+1: 
7. :-1:
8. :+1:
9. :-1:

IMHO sempre que houver um link, o mesmo deve ter uma descrição, se não ele deve ser visto como spam.
