### ISSUE TITLE
Maturidade na comunicação

### ISSUE THREAD

**Issue by renatomefi** [php-brasil/Documentos#8]
Acredito que os administradores e integrantes do grupo devam tomar uma postura mais séria e menos rude na comunicação.
Esta forma de tratar é extremamente ineficiente e demonstra comunicação infantil, além de afastar os novatos também prejudica a imagem do grupo perante outras pessoas e demais comunidades/grupos.
Coisas como "quer aprender e não ser escrotizado no grupo siga este guia" não deveriam existir, todos são capazes de fazer uma comunicação eficiente sem prejudicar a própria imagem e carregar a do grupo consigo.

"Uma comunidade embrutece-se infinitamente mais pelo uso regular da repressão do que pela criminalidade ocasional." Oscar Wilde

Espero ter contrubuído e estou aberto para argumentações.
Renato Mendes Figueiredo
www.renatomefi.com.br

**Comment by kinncj** [comment]
@renatomefidf , concordo que a forma de se expressar deva ser melhor analisada.

A intenção do grupo não é afastar novatos, mas sim promover discussões de alto-nível que não possam ser encontradas em canais de ajuda.

Acredite, se alguém colocou essa frase nas regras (por mais ofensiva que seja), é pelo fato de quem nem todos são capazes de fazer uma comunicação eficiente sem prejudicar a própria imagem ou os interesses do grupo.

**Comment by netojoaobatista** [comment]
Acabei de abrir uma nova issue, @renatomefidf, que está relacionada com essa. A issue #10 é referente à ação que deverá ser tomada.

Nos casos em que for necessário um alerta ou comunicação com o membro, eu concordo com sua sugestão.

**Comment by henriquemoody** [comment]
Minha percepção sobre alguns posts do grupo é que é correto escrotizar um usuário que postou uma pergunta idiota ou que fere as regras do grupo e em outros casos pode ser motivo de banimento do grupo.
A forma de tratar os usuários deve ser uniforme e os moderadores devem ser um bom exemplo de como os outros usuários devem se comportar. As regras devem ser aplicadas à todos, sejam moderadores, sejam novos membros ou membros antigos, caso contrário o grupo fica inconsistente e vira motivo de comentários negativos como já temos visto recentemente.

**Comment by renatomefi** [comment]
Se a liderança não for exemplo, isto vai continuar sendo inerente e nunca haverá uma forma correta.
O meu medo destas atitudes, acontece pois elas denigrem a imagem da comunidade PHP perante todas as outras, e eu acredito que nenhum de nós quer ser referenciado por uma coisa tão negativa.
Mesmo que as pessoas tenham dificuldade de entender as regras (é normal, pois no facebook quase não existem regras), com certeza existe uma maneira melhor de tratar o problema, se existe o esforço para "escrotizar", pode existir o esforço para mandar o link com as regras e pedir para o usuário se retratar.

Enfim, acredito que é válido pensar como isto deve ser tratado, e fico satisfeito que vocês tenham enxergado o problema.

**Comment by kinncj** [comment]
:+1:

**Comment by jackmakiyama** [comment]
@renatomefidf a frase foi minha, concordo contigo, mas o que estava rolando quando foi lançado essa versão das regras a frase se encaixava perfeitamente: era muito novato entrando, nós orientando e eles nos xingando por não saber enxergar seu próprio problema.

Hoje o cenário é outro e veja como está rolando, está sendo justo.

**Comment by filipiarruda** [comment]
@kinncj amigo, acho que deve sim haver uma mudança. Porque como vimos em outras issues, sobre os assuntos que poderão ser tratados no grupo, acho que mesmo que a pessoa desrespeite aquela regra, intencionalmente ou não, não devemos ser rudes, não faz sentido quebrar uma regra para cumprir outra. E também isso irá nos ajudar a crescer como profissionais, mantendo um alto nível de comunicação.
