### ISSUE TITLE
Questões relacionadas com pedidos de sugestões

### ISSUE THREAD

**Issue by netojoaobatista** [php-brasil/Documentos#9]
Quais os tipos de postagens sobre pedidos de sugestões devemos permitir?
1. Pedidos de sugestões de editores ou IDEs.
2. Pedidos de sugestões de empacotadores (Composer, Pear, etc).
3. Pedidos de sugestões de frameworks.
4. Pedidos de sugestões de livros.
5. Pedidos de sugestões de hospedagem.
6. Pedidos de sugestões de cursos presenciais ou onlines (pagos ou não).
7. Pedidos de sugestões de ferramentas prontas (WordPress, Magento, etc).
## 
#### Votação

| Usuário | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| @henriquemoody | :-1: | :-1: | :-1: | :-1: | :-1: | :-1: | :-1: |
| @kinncj | :-1: | :+1: | :-1: | :+1: | :-1: | :-1: | :-1: |

**Comment by kinncj** [comment]
- [x] 2, Não promove auto-promoção e é um tópico atual.
- [x] 4, Promove o conhecimento sem auto-promoção.

Editores, Frameworks, Hospedagem e ferramentas prontas além de gerar flame, tem cunho muito pessoal... varia de pessoa para pessoa e é nesse ponto que a comunidade não consegue ouvir à opinião alheia e muito menos defender o seu ponto de vista sem ofender o outro.

Cursos presenciais ou online, pagos, geram auto-promoção do autor... devera ter algum benefício para os usuários desse grupo e não simplesmente fazer do grupo uma grande lista de email que se possa enviar spam.
Cursos presenciais ou online gratuitos são totalmente válidos, desde que se possa garantir a qualidade do conhecido a ser passado... o grupo não deve promover o compartilhamento de conhecimentos caso o mesmo seja errôneo ou não esteja de acordo com os interesses da comunidade (em poucas palavras, não pode ser um curso bosta que ensina coisas erradas ou ataca outras ferramentas apenas para sua promoção).

**Comment by henriquemoody** [comment]
Acredito que nenhum desses deveria ser permitido, haja visto o que o @kinncj  já falou.
Seria melhor criar um bom documento sobre o assunto anexado as regas do grupo.

**Comment by rogerioadris** [comment]
sou a favor de sugestões livros em forma de enquete, o restante nenhuma.

**Comment by brunogasparetto** [comment]
é como o @kinncj comentou, esses pedidos mais geram flame do que discussões saudáveis, então nem valem a pena.

Sugestões de livros acho válido também num documento separado só pra citar alguns realmente interessantes tanto pra linguagem quanto pra assuntos relacionados.

**Comment by jackmakiyama** [comment]
Compartilho da opinião do @henriquemoody e esse documento já existe:
- [Quero Aprender PHP - Augusto Pascutti](https://www.facebook.com/notes/php-brasil/quero-aprender-php/10151496573755160)
- [PHP: Do Jeito Certo](http://br.phptherightway.com/)

**Comment by filipiarruda** [comment]
Acho todas válidas, mas como disseram acima, tem questões que tem que defender o seu ponto de vista, destacando as vantagens, mas sem ofender a opção de framework, host, ide do outro membro do grupo

**Comment by FredAzevedo** [comment]
Concordo com o Felipe Arruda! Outro ponto bacana é criar um fórum específico, o facebook na minha opinião não é produtivo como um fórum! (Não sei se já existe o fórum, mas se não existir, fica como sugestão). No fórum poderá ter vários tópicos correlacionado a cada área citada a cima... (Frameworks, LIvros, Hospedagens, Cursos, etc).
